name: Newman API Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Create reports folder
        run: mkdir -p Dockerized-API-QA/newman/reports

      - name: Run Newman tests
        run: |
          newman run Dockerized-API-QA/newman/collections/dummyjson.json \
            -e Dockerized-API-QA/newman/environments/dummyjson.env.json \
            -r htmlextra \
            --reporter-htmlextra-export Dockerized-API-QA/newman/reports/report.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: Dockerized-API-QA/newman/reports/report.html