services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"

  newman:
    image: postman/newman
    container_name: newman
    depends_on:
      - api
    volumes:
      - ./newman:/etc/newman
      - ./reports:/etc/reports
    command: >
      run /etc/newman/collections/ci.dumjson.collection.json
      -e /etc/newman/environments/ci.dumjson.env.json
      -r cli, htmlextra
      --reporter-htmlextra-export /etc/reports/report.html