name: Playwright Tests (OpenCart)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: 03-opencart-playwright-ui-automation/playwright-opencart
        run: npm install

      - name: Install Playwright browsers
        working-directory: 03-opencart-playwright-ui-automation/playwright-opencart
        run: npx playwright install --with-deps

      - name: Start OpenCart Docker stack
        working-directory: 03-opencart-playwright-ui-automation/opencart-docker
        run: docker compose up -d

      - name: Show Docker containers
        run: docker ps -a

      - name: Show Docker logs
        working-directory: 03-opencart-playwright-ui-automation/opencart-docker
        run: docker compose logs

      - name: Wait for OpenCart
        run: |
          echo "Waiting for login page..."
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/adminqa)
            echo "Attempt $i status: $STATUS"
                 
            if curl -s http://127.0.0.1/adminqa | grep -q "input-username"; then
              echo "OpenCart is ready"
              exit 0
            fi
                 
            sleep 3
          done
                 
          echo "OpenCart failed to become ready"
          docker compose logs
          exit 1
          
      - name: Run Playwright tests
        working-directory: 03-opencart-playwright-ui-automation/playwright-opencart
        run: npx playwright test -g "Add product successfully" --reporter=line

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report